[tool.poetry]
name = "xepa-crawler"
version = "0.1.0"
description = ""
authors = ["João Pedro Chagas <jpchagas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
scrapy = "^2.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
